// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

/**
 * Normalizes Supabase storage URLs to use the custom domain.
 * This handles cases where full URLs with the old domain might be stored in the database.
 */
export const getSafeImageUrl = (url: string | null | undefined) => {
  if (!url) return undefined;
  if (typeof url !== 'string') return url;

  const oldHost = 'womxlijnyxvfndbyxefc.supabase.co';
  const customHost = 'api.storyseed.in';

  if (url.includes(oldHost)) {
    return url.replace(oldHost, customHost);
  }

  return url;
};
